# swagger_config.yml
swagger: "2.0"
info:
  title: "Minha API Flask"
  description: "API de exemplo com autenticação básica e CRUD de itens"
  version: "1.0.0"
securityDefinitions:
  basicAuth:
    type: "basic"
    description: "Autenticação básica (usuário/senha)"
paths:
  /hello:
    get:
      tags:
        - "Hello"
      security:
        - basicAuth: []
      summary: "Retorna uma mensagem de boas-vindas"
      responses:
        200:
          description: "Sucesso"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Hello World!"
        401:
          description: "Não autorizado"

  /items:
    get:
      tags:
        - "Items"
      summary: "Lista todos os itens"
      responses:
        200:
          description: "Lista de itens"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                id:
                  type: "integer"
                name:
                  type: "string"

    post:
      tags:
        - "Items"
      summary: "Adiciona um novo item"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            properties:
              name:
                type: "string"
              quantity:
                type: "integer"
      responses:
        201:
          description: "Item criado"
          schema:
            type: "object"
            properties:
              name:
                type: "string"
              quantity:
                type: "integer"

  /items/{item_id}:
    put:
      tags:
        - "Items"
      summary: "Atualiza um item"
      parameters:
        - in: "path"
          name: "item_id"
          type: "integer"
          required: true
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            properties:
              name:
                type: "string"
              quantity:
                type: "integer"
      responses:
        200:
          description: "Item atualizado"
        404:
          description: "Item não encontrado"

    delete:
      tags:
        - "Items"
      summary: "Remove um item"
      parameters:
        - in: "path"
          name: "item_id"
          type: "integer"
          required: true
      responses:
        200:
          description: "Item removido"
        404:
          description: "Item não encontrado"

/scrape/title:
    get:
      tags:
        - "Scraping"
      summary: "Extrai o título de uma página web"
      description: "Faz scraping do título HTML de uma URL fornecida"
      security:
        - basicAuth: []
      parameters:
        - in: query
          name: url
          type: string
          required: true
          description: "URL da página para extrair o título"
          example: "https://www.example.com"
      responses:
        200:
          description: "Título extraído com sucesso"
          schema:
            type: object
            properties:
              title:
                type: string
                description: "Título da página"
              url:
                type: string
                description: "URL processada"
        400:
          description: "URL não fornecida"
          schema:
            type: object
            properties:
              error:
                type: string
                example: "URL is required"
        401:
          description: "Não autorizado"
        500:
          description: "Erro ao processar a URL"
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Failed to fetch URL"